# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import plugin_pb2 as plugin__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginServiceStub:
    """-----------------------------------------------------------------------------
    Services
    -----------------------------------------------------------------------------

    PluginService is implemented by the plugin process. The host calls
    these RPCs to drive the plugin's lifecycle. Every call is unary; the
    streaming surface lives on HostService.Subscribe.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/railyard.plugin.v1.PluginService/Init',
                request_serializer=plugin__pb2.InitRequest.SerializeToString,
                response_deserializer=plugin__pb2.InitResponse.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/railyard.plugin.v1.PluginService/Start',
                request_serializer=plugin__pb2.StartRequest.SerializeToString,
                response_deserializer=plugin__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/railyard.plugin.v1.PluginService/Stop',
                request_serializer=plugin__pb2.StopRequest.SerializeToString,
                response_deserializer=plugin__pb2.StopResponse.FromString,
                _registered_method=True)
        self.HandleCommand = channel.unary_unary(
                '/railyard.plugin.v1.PluginService/HandleCommand',
                request_serializer=plugin__pb2.HandleCommandRequest.SerializeToString,
                response_deserializer=plugin__pb2.HandleCommandResponse.FromString,
                _registered_method=True)


class PluginServiceServicer:
    """-----------------------------------------------------------------------------
    Services
    -----------------------------------------------------------------------------

    PluginService is implemented by the plugin process. The host calls
    these RPCs to drive the plugin's lifecycle. Every call is unary; the
    streaming surface lives on HostService.Subscribe.
    """

    def Init(self, request, context):
        """Init is the handshake. The plugin advertises its desired
        capabilities (event subscriptions, command registrations, SDK
        version) and the host returns the subset actually permitted by the
        allow-list along with structured denial reasons for anything
        refused. Init MUST complete before Start is called.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Start signals the host has finished booting core subsystems and the
        plugin may launch any long-lived workers. Start MUST return
        promptly; long-running work belongs in a daemon the plugin
        registers with the host.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop signals shutdown. The plugin SHOULD release resources and
        return within the host's drain timeout (5 seconds in Phase 1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleCommand(self, request, context):
        """HandleCommand is invoked by the host when an external caller
        dispatches a command the plugin registered via Init capabilities.
        The args/result preserve the weakly-typed shape of the Go SDK via
        google.protobuf.Struct.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=plugin__pb2.InitRequest.FromString,
                    response_serializer=plugin__pb2.InitResponse.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=plugin__pb2.StartRequest.FromString,
                    response_serializer=plugin__pb2.StartResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=plugin__pb2.StopRequest.FromString,
                    response_serializer=plugin__pb2.StopResponse.SerializeToString,
            ),
            'HandleCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleCommand,
                    request_deserializer=plugin__pb2.HandleCommandRequest.FromString,
                    response_serializer=plugin__pb2.HandleCommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'railyard.plugin.v1.PluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('railyard.plugin.v1.PluginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginService:
    """-----------------------------------------------------------------------------
    Services
    -----------------------------------------------------------------------------

    PluginService is implemented by the plugin process. The host calls
    these RPCs to drive the plugin's lifecycle. Every call is unary; the
    streaming surface lives on HostService.Subscribe.
    """

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/railyard.plugin.v1.PluginService/Init',
            plugin__pb2.InitRequest.SerializeToString,
            plugin__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/railyard.plugin.v1.PluginService/Start',
            plugin__pb2.StartRequest.SerializeToString,
            plugin__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/railyard.plugin.v1.PluginService/Stop',
            plugin__pb2.StopRequest.SerializeToString,
            plugin__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/railyard.plugin.v1.PluginService/HandleCommand',
            plugin__pb2.HandleCommandRequest.SerializeToString,
            plugin__pb2.HandleCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HostServiceStub:
    """HostService is implemented by the railyard host. The plugin dials
    back into the host over the same multiplexed transport to read state,
    subscribe to events, dispatch core commands, fetch its config block,
    and emit structured log records.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.YardInfo = channel.unary_unary(
                '/railyard.plugin.v1.HostService/YardInfo',
                request_serializer=plugin__pb2.YardInfoRequest.SerializeToString,
                response_deserializer=plugin__pb2.YardInfoResponse.FromString,
                _registered_method=True)
        self.Snapshot = channel.unary_unary(
                '/railyard.plugin.v1.HostService/Snapshot',
                request_serializer=plugin__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=plugin__pb2.SnapshotResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/railyard.plugin.v1.HostService/Subscribe',
                request_serializer=plugin__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=plugin__pb2.Event.FromString,
                _registered_method=True)
        self.DispatchCommand = channel.unary_unary(
                '/railyard.plugin.v1.HostService/DispatchCommand',
                request_serializer=plugin__pb2.DispatchCommandRequest.SerializeToString,
                response_deserializer=plugin__pb2.DispatchCommandResponse.FromString,
                _registered_method=True)
        self.Config = channel.unary_unary(
                '/railyard.plugin.v1.HostService/Config',
                request_serializer=plugin__pb2.ConfigRequest.SerializeToString,
                response_deserializer=plugin__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.Log = channel.unary_unary(
                '/railyard.plugin.v1.HostService/Log',
                request_serializer=plugin__pb2.LogRequest.SerializeToString,
                response_deserializer=plugin__pb2.LogResponse.FromString,
                _registered_method=True)
        self.EmitEvent = channel.unary_unary(
                '/railyard.plugin.v1.HostService/EmitEvent',
                request_serializer=plugin__pb2.EmitEventRequest.SerializeToString,
                response_deserializer=plugin__pb2.EmitEventResponse.FromString,
                _registered_method=True)


class HostServiceServicer:
    """HostService is implemented by the railyard host. The plugin dials
    back into the host over the same multiplexed transport to read state,
    subscribe to events, dispatch core commands, fetch its config block,
    and emit structured log records.
    """

    def YardInfo(self, request, context):
        """YardInfo returns the static identity of this railyard instance.
        The result is fixed for the lifetime of the host; plugins typically
        cache it after the first call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Snapshot(self, request, context):
        """Snapshot returns the current full yard state in a single read
        transaction. The shape mirrors pkg/plugin.Snapshot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe opens a server-streamed multiplexed event channel. The
        plugin asks for the intersection of its allow-list and the topics
        it cares about; the host fans events from the internal bus into
        the stream until the plugin cancels.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DispatchCommand(self, request, context):
        """DispatchCommand invokes a command by name. The host first looks up
        the name in the Phase 1 core allow-list, then in plugin-registered
        commands. Validation errors are returned in the response, not as a
        gRPC error.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Config(self, request, context):
        """Config returns the raw yaml bytes of the named plugin's top-level
        config block from railyard.yaml. The plugin SDK rehydrates the
        bytes into a yaml.Node so the in-process Host.Config signature
        remains stable for plugin authors. If no block is configured, the
        response carries `present = false` and an empty payload.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Log(self, request, context):
        """Log accepts a structured log record from the plugin. The host
        re-emits the record through its own slog handler with a
        "plugin=<name>" attribute already set by the host wrapper.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmitEvent(self, request, context):
        """EmitEvent lets a plugin publish a namespaced event onto the internal
        bus so other plugins (and core) can observe it. The topic MUST be
        prefixed with the caller's own "<plugin>." name; the host derives
        the name from the connection-bound identity, NEVER from a request
        field, and returns PermissionDenied for an un-prefixed topic or one
        the plugin's allow.publish list does not permit (railyard-77h.9).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'YardInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.YardInfo,
                    request_deserializer=plugin__pb2.YardInfoRequest.FromString,
                    response_serializer=plugin__pb2.YardInfoResponse.SerializeToString,
            ),
            'Snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=plugin__pb2.SnapshotRequest.FromString,
                    response_serializer=plugin__pb2.SnapshotResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=plugin__pb2.SubscribeRequest.FromString,
                    response_serializer=plugin__pb2.Event.SerializeToString,
            ),
            'DispatchCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.DispatchCommand,
                    request_deserializer=plugin__pb2.DispatchCommandRequest.FromString,
                    response_serializer=plugin__pb2.DispatchCommandResponse.SerializeToString,
            ),
            'Config': grpc.unary_unary_rpc_method_handler(
                    servicer.Config,
                    request_deserializer=plugin__pb2.ConfigRequest.FromString,
                    response_serializer=plugin__pb2.ConfigResponse.SerializeToString,
            ),
            'Log': grpc.unary_unary_rpc_method_handler(
                    servicer.Log,
                    request_deserializer=plugin__pb2.LogRequest.FromString,
                    response_serializer=plugin__pb2.LogResponse.SerializeToString,
            ),
            'EmitEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitEvent,
                    request_deserializer=plugin__pb2.EmitEventRequest.FromString,
                    response_serializer=plugin__pb2.EmitEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'railyard.plugin.v1.HostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('railyard.plugin.v1.HostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HostService:
    """HostService is implemented by the railyard host. The plugin dials
    back into the host over the same multiplexed transport to read state,
    subscribe to events, dispatch core commands, fetch its config block,
    and emit structured log records.
    """

    @staticmethod
    def YardInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/railyard.plugin.v1.HostService/YardInfo',
            plugin__pb2.YardInfoRequest.SerializeToString,
            plugin__pb2.YardInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/railyard.plugin.v1.HostService/Snapshot',
            plugin__pb2.SnapshotRequest.SerializeToString,
            plugin__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/railyard.plugin.v1.HostService/Subscribe',
            plugin__pb2.SubscribeRequest.SerializeToString,
            plugin__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DispatchCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/railyard.plugin.v1.HostService/DispatchCommand',
            plugin__pb2.DispatchCommandRequest.SerializeToString,
            plugin__pb2.DispatchCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Config(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/railyard.plugin.v1.HostService/Config',
            plugin__pb2.ConfigRequest.SerializeToString,
            plugin__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/railyard.plugin.v1.HostService/Log',
            plugin__pb2.LogRequest.SerializeToString,
            plugin__pb2.LogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmitEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/railyard.plugin.v1.HostService/EmitEvent',
            plugin__pb2.EmitEventRequest.SerializeToString,
            plugin__pb2.EmitEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
