{{- if .Values.dolt.internal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "railyard.fullname" . }}-dolt-init
  labels:
    {{- include "railyard.labels" . | nindent 4 }}
    app.kubernetes.io/component: dolt
data:
  01-create-remote-user.sql: |
    CREATE DATABASE IF NOT EXISTS `{{ include "railyard.doltDatabase" . }}`;
    CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '{{ .Values.dolt.password }}';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
{{- end }}
