{{- if .Values.database.internal }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "railyard.fullname" . }}-mysql
  labels:
    {{- include "railyard.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  serviceName: {{ include "railyard.fullname" . }}-mysql
  replicas: 1
  selector:
    matchLabels:
      {{- include "railyard.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        {{- include "railyard.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - name: mysql
              containerPort: {{ .Values.database.port }}
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "railyard.fullname" . }}-db
                  key: db-password
          readinessProbe:
            tcpSocket:
              port: mysql
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: mysql
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          {{- with .Values.database.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: mysql-init
          configMap:
            name: {{ include "railyard.fullname" . }}-mysql-init
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.database.storage.storageClass }}
        storageClassName: {{ .Values.database.storage.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.database.storage.size }}
{{- end }}
