{{- if .Values.dashboard.oauth2proxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "railyard.fullname" . }}-oauth2proxy
  labels:
    {{- include "railyard.labels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
type: Opaque
stringData:
  client-id: {{ .Values.dashboard.oauth2proxy.clientID | quote }}
  client-secret: {{ .Values.dashboard.oauth2proxy.clientSecret | quote }}
  cookie-secret: {{ .Values.dashboard.oauth2proxy.cookieSecret | quote }}
{{- end }}
