apiVersion: v1
kind: Secret
metadata:
  name: {{ include "railyard.fullname" . }}-db
  labels:
    {{- include "railyard.labels" . | nindent 4 }}
type: Opaque
stringData:
  dolt-username: {{ .Values.dolt.username | quote }}
  dolt-password: {{ .Values.dolt.password | quote }}
  dolt-database: {{ include "railyard.doltDatabase" . | quote }}
  pgvector-username: {{ .Values.pgvector.username | quote }}
  pgvector-password: {{ .Values.pgvector.password | quote }}
  pgvector-database: {{ .Values.pgvector.database | quote }}
