apiVersion: v1
kind: Secret
metadata:
  name: {{ include "railyard.fullname" . }}-db
  labels:
    {{- include "railyard.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-username: {{ .Values.database.username | quote }}
  db-password: {{ .Values.database.password | quote }}
  db-database: {{ include "railyard.dbDatabase" . | quote }}
  pgvector-username: {{ .Values.pgvector.username | quote }}
  pgvector-password: {{ .Values.pgvector.password | quote }}
  pgvector-database: {{ .Values.pgvector.database | quote }}
