// Package railyard.plugin.v1 is the wire contract between a railyard
// host and an out-of-process plugin spoken over gRPC on a Unix domain
// socket. The Go SDK (pkg/plugin) wraps these RPCs in the same
// signatures that in-process plugins use today; the proto contract is
// the source of truth for what crosses the process boundary.
//
// Wire-compat policy (see docs/plugins/proto.md):
//
//   - Adding fields, enum values, oneof arms, or messages is additive
//     and SHOULD remain wire-compatible. New senders/old receivers will
//     observe defaults or unknown-field skips.
//   - Renaming or renumbering an existing field is breaking and forces
//     a new v2 package.
//   - Removing a field requires reserving its number and name so it
//     can never be reused on the v1 wire.
//   - `buf breaking` runs against the last-merged contract on the main
//     branch (`--against '.git#branch=main'`) on every change, so a
//     wire-incompatible edit is caught even when the proto and any local
//     baseline are touched in the same commit; see docs/plugins/proto.md.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: plugin.proto

package protov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_Init_FullMethodName          = "/railyard.plugin.v1.PluginService/Init"
	PluginService_Start_FullMethodName         = "/railyard.plugin.v1.PluginService/Start"
	PluginService_Stop_FullMethodName          = "/railyard.plugin.v1.PluginService/Stop"
	PluginService_HandleCommand_FullMethodName = "/railyard.plugin.v1.PluginService/HandleCommand"
	PluginService_Health_FullMethodName        = "/railyard.plugin.v1.PluginService/Health"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginService is implemented by the plugin process. The host calls
// these RPCs to drive the plugin's lifecycle. Every call is unary; the
// streaming surface lives on HostService.Subscribe.
type PluginServiceClient interface {
	// Init is the handshake. The plugin advertises its desired
	// capabilities (event subscriptions, command registrations, SDK
	// version) and the host returns the subset actually permitted by the
	// allow-list along with structured denial reasons for anything
	// refused. Init MUST complete before Start is called.
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	// Start signals the host has finished booting core subsystems and the
	// plugin may launch any long-lived workers. Start MUST return
	// promptly; long-running work belongs in a daemon the plugin
	// registers with the host.
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// Stop signals shutdown. The plugin SHOULD release resources and
	// return within the host's drain timeout (5 seconds in Phase 1).
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// HandleCommand is invoked by the host when an external caller
	// dispatches a command the plugin registered via Init capabilities.
	// The args/result preserve the weakly-typed shape of the Go SDK via
	// google.protobuf.Struct.
	HandleCommand(ctx context.Context, in *HandleCommandRequest, opts ...grpc.CallOption) (*HandleCommandResponse, error)
	// Health is an OPTIONAL liveness/functional probe the host polls on a
	// configurable interval (default 30s) so operators can see whether a
	// running plugin is actually functional — not merely "process alive"
	// (railyard-77h.12). A plugin opts in by implementing the SDK's
	// pkg/plugin.HealthReporter interface; the plugin-side adapter returns
	// codes.Unimplemented when the user impl does NOT implement it, which
	// the host surfaces as "n/a" rather than an error. This keeps plugins
	// built before this RPC fully backward compatible. The host uses a 2s
	// deadline per probe; a timeout or transport error is mapped to
	// HEALTH_DEGRADED with the error text.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, PluginService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, PluginService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, PluginService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) HandleCommand(ctx context.Context, in *HandleCommandRequest, opts ...grpc.CallOption) (*HandleCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleCommandResponse)
	err := c.cc.Invoke(ctx, PluginService_HandleCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PluginService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
//
// PluginService is implemented by the plugin process. The host calls
// these RPCs to drive the plugin's lifecycle. Every call is unary; the
// streaming surface lives on HostService.Subscribe.
type PluginServiceServer interface {
	// Init is the handshake. The plugin advertises its desired
	// capabilities (event subscriptions, command registrations, SDK
	// version) and the host returns the subset actually permitted by the
	// allow-list along with structured denial reasons for anything
	// refused. Init MUST complete before Start is called.
	Init(context.Context, *InitRequest) (*InitResponse, error)
	// Start signals the host has finished booting core subsystems and the
	// plugin may launch any long-lived workers. Start MUST return
	// promptly; long-running work belongs in a daemon the plugin
	// registers with the host.
	Start(context.Context, *StartRequest) (*StartResponse, error)
	// Stop signals shutdown. The plugin SHOULD release resources and
	// return within the host's drain timeout (5 seconds in Phase 1).
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	// HandleCommand is invoked by the host when an external caller
	// dispatches a command the plugin registered via Init capabilities.
	// The args/result preserve the weakly-typed shape of the Go SDK via
	// google.protobuf.Struct.
	HandleCommand(context.Context, *HandleCommandRequest) (*HandleCommandResponse, error)
	// Health is an OPTIONAL liveness/functional probe the host polls on a
	// configurable interval (default 30s) so operators can see whether a
	// running plugin is actually functional — not merely "process alive"
	// (railyard-77h.12). A plugin opts in by implementing the SDK's
	// pkg/plugin.HealthReporter interface; the plugin-side adapter returns
	// codes.Unimplemented when the user impl does NOT implement it, which
	// the host surfaces as "n/a" rather than an error. This keeps plugins
	// built before this RPC fully backward compatible. The host uses a 2s
	// deadline per probe; a timeout or transport error is mapped to
	// HEALTH_DEGRADED with the error text.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedPluginServiceServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedPluginServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedPluginServiceServer) HandleCommand(context.Context, *HandleCommandRequest) (*HandleCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleCommand not implemented")
}
func (UnimplementedPluginServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_HandleCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).HandleCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_HandleCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).HandleCommand(ctx, req.(*HandleCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "railyard.plugin.v1.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _PluginService_Init_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _PluginService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _PluginService_Stop_Handler,
		},
		{
			MethodName: "HandleCommand",
			Handler:    _PluginService_HandleCommand_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PluginService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	HostService_YardInfo_FullMethodName        = "/railyard.plugin.v1.HostService/YardInfo"
	HostService_Snapshot_FullMethodName        = "/railyard.plugin.v1.HostService/Snapshot"
	HostService_Subscribe_FullMethodName       = "/railyard.plugin.v1.HostService/Subscribe"
	HostService_DispatchCommand_FullMethodName = "/railyard.plugin.v1.HostService/DispatchCommand"
	HostService_Config_FullMethodName          = "/railyard.plugin.v1.HostService/Config"
	HostService_Log_FullMethodName             = "/railyard.plugin.v1.HostService/Log"
	HostService_EmitEvent_FullMethodName       = "/railyard.plugin.v1.HostService/EmitEvent"
	HostService_KVGet_FullMethodName           = "/railyard.plugin.v1.HostService/KVGet"
	HostService_KVPut_FullMethodName           = "/railyard.plugin.v1.HostService/KVPut"
	HostService_KVDelete_FullMethodName        = "/railyard.plugin.v1.HostService/KVDelete"
	HostService_KVList_FullMethodName          = "/railyard.plugin.v1.HostService/KVList"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostService is implemented by the railyard host. The plugin dials
// back into the host over the same multiplexed transport to read state,
// subscribe to events, dispatch core commands, fetch its config block,
// and emit structured log records.
type HostServiceClient interface {
	// YardInfo returns the static identity of this railyard instance.
	// The result is fixed for the lifetime of the host; plugins typically
	// cache it after the first call.
	YardInfo(ctx context.Context, in *YardInfoRequest, opts ...grpc.CallOption) (*YardInfoResponse, error)
	// Snapshot returns the current full yard state in a single read
	// transaction. The shape mirrors pkg/plugin.Snapshot.
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// Subscribe opens a server-streamed multiplexed event channel. The
	// plugin asks for the intersection of its allow-list and the topics
	// it cares about; the host fans events from the internal bus into
	// the stream until the plugin cancels.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// DispatchCommand invokes a command by name. The host first looks up
	// the name in the Phase 1 core allow-list, then in plugin-registered
	// commands. Validation errors are returned in the response, not as a
	// gRPC error.
	DispatchCommand(ctx context.Context, in *DispatchCommandRequest, opts ...grpc.CallOption) (*DispatchCommandResponse, error)
	// Config returns the raw yaml bytes of the named plugin's top-level
	// config block from railyard.yaml. The plugin SDK rehydrates the
	// bytes into a yaml.Node so the in-process Host.Config signature
	// remains stable for plugin authors. If no block is configured, the
	// response carries `present = false` and an empty payload.
	Config(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	// Log accepts a structured log record from the plugin. The host
	// re-emits the record through its own slog handler with a
	// "plugin=<name>" attribute already set by the host wrapper.
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	// EmitEvent lets a plugin publish a namespaced event onto the internal
	// bus so other plugins (and core) can observe it. The topic MUST be
	// prefixed with the caller's own "<plugin>." name; the host derives
	// the name from the connection-bound identity, NEVER from a request
	// field, and returns PermissionDenied for an un-prefixed topic or one
	// the plugin's allow.publish list does not permit (railyard-77h.9).
	EmitEvent(ctx context.Context, in *EmitEventRequest, opts ...grpc.CallOption) (*EmitEventResponse, error)
	// KVGet reads one value from the plugin's private key/value namespace
	// (railyard-77h.11). The namespace is the caller's connection-bound
	// identity, NEVER a request field, so a plugin can only ever read its
	// own keys. found=false means the key is absent. A host with no DB
	// configured returns codes.Unavailable.
	KVGet(ctx context.Context, in *KVGetRequest, opts ...grpc.CallOption) (*KVGetResponse, error)
	// KVPut writes (inserts or overwrites) one value in the plugin's
	// private namespace. The host enforces per-plugin limits (max value
	// bytes, max key bytes, max key count) and rejects overruns with
	// codes.ResourceExhausted / codes.InvalidArgument (railyard-77h.11).
	KVPut(ctx context.Context, in *KVPutRequest, opts ...grpc.CallOption) (*KVPutResponse, error)
	// KVDelete removes one key from the plugin's private namespace.
	// Deleting an absent key is a no-op (no error) (railyard-77h.11).
	KVDelete(ctx context.Context, in *KVDeleteRequest, opts ...grpc.CallOption) (*KVDeleteResponse, error)
	// KVList returns the keys in the plugin's private namespace whose name
	// begins with the given prefix (empty prefix lists all keys), sorted
	// ascending (railyard-77h.11).
	KVList(ctx context.Context, in *KVListRequest, opts ...grpc.CallOption) (*KVListResponse, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) YardInfo(ctx context.Context, in *YardInfoRequest, opts ...grpc.CallOption) (*YardInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YardInfoResponse)
	err := c.cc.Invoke(ctx, HostService_YardInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, HostService_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostService_ServiceDesc.Streams[0], HostService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostService_SubscribeClient = grpc.ServerStreamingClient[Event]

func (c *hostServiceClient) DispatchCommand(ctx context.Context, in *DispatchCommandRequest, opts ...grpc.CallOption) (*DispatchCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchCommandResponse)
	err := c.cc.Invoke(ctx, HostService_DispatchCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Config(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, HostService_Config_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, HostService_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) EmitEvent(ctx context.Context, in *EmitEventRequest, opts ...grpc.CallOption) (*EmitEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitEventResponse)
	err := c.cc.Invoke(ctx, HostService_EmitEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) KVGet(ctx context.Context, in *KVGetRequest, opts ...grpc.CallOption) (*KVGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVGetResponse)
	err := c.cc.Invoke(ctx, HostService_KVGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) KVPut(ctx context.Context, in *KVPutRequest, opts ...grpc.CallOption) (*KVPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVPutResponse)
	err := c.cc.Invoke(ctx, HostService_KVPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) KVDelete(ctx context.Context, in *KVDeleteRequest, opts ...grpc.CallOption) (*KVDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVDeleteResponse)
	err := c.cc.Invoke(ctx, HostService_KVDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) KVList(ctx context.Context, in *KVListRequest, opts ...grpc.CallOption) (*KVListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVListResponse)
	err := c.cc.Invoke(ctx, HostService_KVList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility.
//
// HostService is implemented by the railyard host. The plugin dials
// back into the host over the same multiplexed transport to read state,
// subscribe to events, dispatch core commands, fetch its config block,
// and emit structured log records.
type HostServiceServer interface {
	// YardInfo returns the static identity of this railyard instance.
	// The result is fixed for the lifetime of the host; plugins typically
	// cache it after the first call.
	YardInfo(context.Context, *YardInfoRequest) (*YardInfoResponse, error)
	// Snapshot returns the current full yard state in a single read
	// transaction. The shape mirrors pkg/plugin.Snapshot.
	Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	// Subscribe opens a server-streamed multiplexed event channel. The
	// plugin asks for the intersection of its allow-list and the topics
	// it cares about; the host fans events from the internal bus into
	// the stream until the plugin cancels.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error
	// DispatchCommand invokes a command by name. The host first looks up
	// the name in the Phase 1 core allow-list, then in plugin-registered
	// commands. Validation errors are returned in the response, not as a
	// gRPC error.
	DispatchCommand(context.Context, *DispatchCommandRequest) (*DispatchCommandResponse, error)
	// Config returns the raw yaml bytes of the named plugin's top-level
	// config block from railyard.yaml. The plugin SDK rehydrates the
	// bytes into a yaml.Node so the in-process Host.Config signature
	// remains stable for plugin authors. If no block is configured, the
	// response carries `present = false` and an empty payload.
	Config(context.Context, *ConfigRequest) (*ConfigResponse, error)
	// Log accepts a structured log record from the plugin. The host
	// re-emits the record through its own slog handler with a
	// "plugin=<name>" attribute already set by the host wrapper.
	Log(context.Context, *LogRequest) (*LogResponse, error)
	// EmitEvent lets a plugin publish a namespaced event onto the internal
	// bus so other plugins (and core) can observe it. The topic MUST be
	// prefixed with the caller's own "<plugin>." name; the host derives
	// the name from the connection-bound identity, NEVER from a request
	// field, and returns PermissionDenied for an un-prefixed topic or one
	// the plugin's allow.publish list does not permit (railyard-77h.9).
	EmitEvent(context.Context, *EmitEventRequest) (*EmitEventResponse, error)
	// KVGet reads one value from the plugin's private key/value namespace
	// (railyard-77h.11). The namespace is the caller's connection-bound
	// identity, NEVER a request field, so a plugin can only ever read its
	// own keys. found=false means the key is absent. A host with no DB
	// configured returns codes.Unavailable.
	KVGet(context.Context, *KVGetRequest) (*KVGetResponse, error)
	// KVPut writes (inserts or overwrites) one value in the plugin's
	// private namespace. The host enforces per-plugin limits (max value
	// bytes, max key bytes, max key count) and rejects overruns with
	// codes.ResourceExhausted / codes.InvalidArgument (railyard-77h.11).
	KVPut(context.Context, *KVPutRequest) (*KVPutResponse, error)
	// KVDelete removes one key from the plugin's private namespace.
	// Deleting an absent key is a no-op (no error) (railyard-77h.11).
	KVDelete(context.Context, *KVDeleteRequest) (*KVDeleteResponse, error)
	// KVList returns the keys in the plugin's private namespace whose name
	// begins with the given prefix (empty prefix lists all keys), sorted
	// ascending (railyard-77h.11).
	KVList(context.Context, *KVListRequest) (*KVListResponse, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServiceServer struct{}

func (UnimplementedHostServiceServer) YardInfo(context.Context, *YardInfoRequest) (*YardInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method YardInfo not implemented")
}
func (UnimplementedHostServiceServer) Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedHostServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedHostServiceServer) DispatchCommand(context.Context, *DispatchCommandRequest) (*DispatchCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchCommand not implemented")
}
func (UnimplementedHostServiceServer) Config(context.Context, *ConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Config not implemented")
}
func (UnimplementedHostServiceServer) Log(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedHostServiceServer) EmitEvent(context.Context, *EmitEventRequest) (*EmitEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmitEvent not implemented")
}
func (UnimplementedHostServiceServer) KVGet(context.Context, *KVGetRequest) (*KVGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KVGet not implemented")
}
func (UnimplementedHostServiceServer) KVPut(context.Context, *KVPutRequest) (*KVPutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KVPut not implemented")
}
func (UnimplementedHostServiceServer) KVDelete(context.Context, *KVDeleteRequest) (*KVDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KVDelete not implemented")
}
func (UnimplementedHostServiceServer) KVList(context.Context, *KVListRequest) (*KVListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KVList not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}
func (UnimplementedHostServiceServer) testEmbeddedByValue()                     {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	// If the following call panics, it indicates UnimplementedHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_YardInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YardInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).YardInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_YardInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).YardInfo(ctx, req.(*YardInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostService_SubscribeServer = grpc.ServerStreamingServer[Event]

func _HostService_DispatchCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).DispatchCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_DispatchCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).DispatchCommand(ctx, req.(*DispatchCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Config_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Config(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_EmitEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).EmitEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_EmitEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).EmitEvent(ctx, req.(*EmitEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_KVGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).KVGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_KVGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).KVGet(ctx, req.(*KVGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_KVPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).KVPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_KVPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).KVPut(ctx, req.(*KVPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_KVDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).KVDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_KVDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).KVDelete(ctx, req.(*KVDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_KVList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).KVList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_KVList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).KVList(ctx, req.(*KVListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "railyard.plugin.v1.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "YardInfo",
			Handler:    _HostService_YardInfo_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _HostService_Snapshot_Handler,
		},
		{
			MethodName: "DispatchCommand",
			Handler:    _HostService_DispatchCommand_Handler,
		},
		{
			MethodName: "Config",
			Handler:    _HostService_Config_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _HostService_Log_Handler,
		},
		{
			MethodName: "EmitEvent",
			Handler:    _HostService_EmitEvent_Handler,
		},
		{
			MethodName: "KVGet",
			Handler:    _HostService_KVGet_Handler,
		},
		{
			MethodName: "KVPut",
			Handler:    _HostService_KVPut_Handler,
		},
		{
			MethodName: "KVDelete",
			Handler:    _HostService_KVDelete_Handler,
		},
		{
			MethodName: "KVList",
			Handler:    _HostService_KVList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _HostService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
